Repository tgrey2024/2503-hackathon-team1, pull requests merged in 2025-03, with the labels that each got.

#18 Delete unused index.html page
  index.html
Labels: could-have

#22 Add FlyonUI integration to Tailwind CSS configuration
  templates/base.html
  theme/static_src/package-lock.json
  theme/static_src/package.json
  theme/static_src/tailwind.config.js
Labels: should-have

#32 Add Django Unfold with Tailwind Admin Panel
  project_root/settings.py
  static/CSS/admin.css
  timeline/admin.py
  timeline/migrations/0001_initial.py
Labels: enhancement

#33 Add Honour Feature to Timeline
  project_root/settings.py
  requirements.txt
  static/js/flyonui.js
  static/js/script.js
  templates/base.html
  timeline/admin.py
  timeline/migrations/0002_alter_timeline_description_alter_timeline_event_and_more.py
  timeline/models.py
  timeline/templates/timeline/timeline.html
  timeline/tests.py
  timeline/urls.py
  timeline/views.py
  utils/timeline.py
Labels: enhancement

#34 Update readme
  README.md
Labels: documentation

#40 Fix login backend in registration process and update admin site title and header
  accounts/views.py
  project_root/settings.py
  requirements.txt
  timeline/migrations/0002_alter_timeline_description_alter_timeline_event_and_more.py
  timeline/migrations/0003_alter_timeline_description_alter_timeline_event_and_more.py
Labels: bug

#41 Add new wireframes, logo and favicon images
  documentation/wireframes/wf_timeline_ipad.png
  documentation/wireframes/wf_timeline_laptop.png
  documentation/wireframes/wf_timeline_mobile.png
  requirements.txt
  static/images/favicon_io/android-chrome-192x192.png
  static/images/favicon_io/android-chrome-512x512.png
  static/images/favicon_io/apple-touch-icon.png
  static/images/favicon_io/favicon-16x16.png
  static/images/favicon_io/favicon-32x32.png
  static/images/favicon_io/favicon.ico
  static/images/logo.png
  static/images/logo_transparentbg.png
Labels: documentation

#47 Remove Accounts App and Update Allauth Integration
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/forms.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/templates/accounts/register.html
  accounts/tests.py
  accounts/urls.py
  accounts/views.py
  project_root/settings.py
  project_root/urls.py
  static/CSS/account.css
  static/js/script.js
  templates/account/base.html
  templates/account/login.html
  templates/account/logout.html
  templates/account/password_change.html
  templates/account/signup.html
  templates/base.html
  timeline/templates/timeline/timeline.html
Labels: must-have

#48 Fix selector for honour count
  static/js/script.js
Labels: bug

#55 Add mentors app with it's features
  mentors/__init__.py
  mentors/admin.py
  mentors/apps.py
  mentors/forms.py
  mentors/migrations/0001_initial.py
  mentors/migrations/__init__.py
  mentors/models.py
  mentors/templates/mentors/contact_form.html
  mentors/templates/mentors/contact_success.html
  mentors/templates/mentors/mentors.html
  mentors/tests.py
  mentors/urls.py
  mentors/views.py
  project_root/settings.py
  project_root/urls.py
  templates/base.html
Labels: must-have

#56 Update README.md
  README.md
Labels: documentation

#76 Update header layout and adjust image size and update event title styling
  templates/base.html
  timeline/templates/timeline/honour.html
Labels: enhancement

#86 Fix honor button state not updating without refreshing the page
  home/templates/home/index.html
  static/js/script.js
Labels: bug
